### ISSUE TITLE
Startup: "ProgrammingError: relation "trans_project" does not exist"

### ISSUE THREAD

**Issue by mobidev111** [nijel/weblate-docker#1]
Just cloned the project & following error appears:

```
[18/Aug/2015 17:40:47]"GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/app/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/app/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/app/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/app/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/local/lib/python2.7/site-packages/weblate/urls.py", line 31, in <module>
    from weblate.sitemaps import SITEMAPS
  File "/app/local/lib/python2.7/site-packages/weblate/sitemaps.py", line 27, in <module>
    'queryset': Project.objects.all_acl(None),
  File "/app/local/lib/python2.7/site-packages/weblate/trans/models/project.py", line 45, in all_acl
    return self.get_acl_status(user)[0]
  File "/app/local/lib/python2.7/site-packages/weblate/trans/models/project.py", line 61, in get_acl_status
    project.id for project in projects if project.has_acl(user)
  File "/app/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/app/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/app/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/app/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/app/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/app/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "trans_project" does not exist
LINE 1: ..."."enable_hooks", "trans_project"."owner_id" FROM "trans_pro...
                                                             ^

[18/Aug/2015 17:41:03]"GET / HTTP/1.1" 500 59
```

**Comment by mobidev111** [comment]
potentially related: "weblate-db_1  | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
weblate-db_1  | "

**Comment by mobidev111** [comment]
For the readme:

* stop the VM - if not yet stopped
docker-machine stop default

* For Mac OSX: enable port forwarding to access the weblate 8000 port:
VBoxManage modifyvm "default" --natpf1 "tcp-port8000,tcp,,8000,,8000";

* start VM
docker-machine start default

* start weblate
- first start containers, then issue the run migrate command
docker-machine env default
eval "$(docker-machine env default)"
docker-compose up

* create weblate database (run only once)
docker-compose run weblate-web migrate

**Comment by mobidev111** [comment]
using docker 1.8.1

**Comment by mobidev111** [comment]
Is there a default admin user? password? please add to readme - or did I oversee this?

**Comment by mobidev111** [comment]
@nijel bump.

**Comment by nijel** [comment]
Feel free to open pull requests for documentation, it's in Git: https://github.com/nijel/weblate/blob/master/docs/admin/install.rst

Admin user has to be created, it's now also documented.
