### ISSUE TITLE
Please update docker configuration for weblate 2.6 

### ISSUE THREAD

**Issue by stepan-romankov** [nijel/weblate-docker#10]
Hi,

I tried to update web late to 2.6 but I'm not so familiar with Python so my attempt wasn't successful (something we incompatibility of dependencies).

**Comment by stepan-romankov** [comment]
Thanks, but when i tried to follow this guide https://docs.weblate.org/en/latest/admin/deployments.html#weblate-and-docker I got an error during "**docker-compose run weblate migrate**"

I added "python-memcached==1.57" to requirements.txt but then "**docker-compose run weblate migrate**" failed with:
`
Traceback (most recent call last):
  File "/app/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/app/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/app/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/app/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 306, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/app/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0016_add-api-keys dependencies reference nonexistent parent node (u'authtoken', u'0001_initial')
`

**Comment by nijel** [comment]
Please wait a bit, this is still work in progress :-).

**Comment by nijel** [comment]
Hmm, it builds now fine, but the testsuite still fails, though I'm not sure why...
