### ISSUE TITLE
failed at docker-compose up

### ISSUE THREAD

**Issue by haifengkao** [nijel/weblate-docker#4]
I have followed the instruction of  [the doc](https://docs.weblate.org/en/latest/admin/deployments.html#docker) until step 4 shows `FATAL:  password authentication failed for user "weblate"`

The full log is 
```
Starting weblatedocker_cache_1...
Recreating weblatedocker_database_1...
Recreating weblatedocker_weblate_1...
Attaching to weblatedocker_cache_1, weblatedocker_database_1, weblatedocker_weblate_1
cache_1    | Signal handled: Terminated.
database_1 | LOG:  database system was interrupted; last known up at 2015-09-23 11:51:30 UTC
database_1 | LOG:  database system was not properly shut down; automatic recovery in progress
database_1 | LOG:  record with zero length at 0/16C2FC0
database_1 | LOG:  redo is not required
database_1 | LOG:  MultiXact member wraparound protections are now enabled
database_1 | LOG:  database system is ready to accept connections
database_1 | LOG:  autovacuum launcher started
database_1 | LOG:  incomplete startup packet
database_1 | LOG:  incomplete startup packet
weblate_1  | 2015/09/23 11:54:53 TCP: Service DATABASE_PORT_5432 (172.17.0.16:5432) is up
database_1 | LOG:  incomplete startup packet
weblate_1  | 2015/09/23 11:54:53 TCP: Service WEBLATEDOCKER_CACHE_1_PORT_11211 (172.17.0.15:11211) is up
weblate_1  | 2015/09/23 11:54:53 TCP: Service CACHE_PORT_11211 (172.17.0.15:11211) is up
weblate_1  | 2015/09/23 11:54:53 TCP: Service WEBLATEDOCKER_DATABASE_1_PORT_5432 (172.17.0.16:5432) is up
weblate_1  | 2015/09/23 11:54:53 TCP: Service CACHE_1_PORT_11211 (172.17.0.15:11211) is up
weblate_1  | 2015/09/23 11:54:53 TCP: Service DATABASE_1_PORT_5432 (172.17.0.16:5432) is up
weblate_1  | 2015/09/23 11:54:53 All services are up!
database_1 | FATAL:  password authentication failed for user "weblate"
database_1 | DETAIL:  Connection matched pg_hba.conf line 95: "host all all 0.0.0.0/0 md5"
weblate_1  | Unhandled exception in thread started by <function wrapper at 0x7f0ac08827d0>
weblate_1  | Performing system checks...
weblate_1  | 
weblate_1  | System check identified no issues (0 silenced).
weblate_1  | Traceback (most recent call last):
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
weblate_1  |     fn(*args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
weblate_1  |     self.check_migrations()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 164, in check_migrations
weblate_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
weblate_1  |     self.loader = MigrationLoader(self.connection)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
weblate_1  |     self.build_graph()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 182, in build_graph
weblate_1  |     self.applied_migrations = recorder.applied_migrations()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
weblate_1  |     self.ensure_schema()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
weblate_1  |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
weblate_1  |     cursor = self.make_debug_cursor(self._cursor())
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
weblate_1  |     self.ensure_connection()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
weblate_1  |     self.connect()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
weblate_1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
weblate_1  |     self.connect()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
weblate_1  |     self.connection = self.get_new_connection(conn_params)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
weblate_1  |     connection = Database.connect(**conn_params)
weblate_1  |   File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
weblate_1  |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
weblate_1  | django.db.utils.OperationalError: FATAL:  password authentication failed for user "weblate"
weblate_1  | 
```

**Comment by haifengkao** [comment]
It works after I changed the default password of postgres in weblate/environment

**Comment by nijel** [comment]
Could you please add something that would cover this for our docs? I don't really know Docker, so this would help others with the setup.

See https://github.com/nijel/weblate/blob/master/docs/admin/deployments.rst#weblate-and-docker

**Comment by haifengkao** [comment]
ok. I will sent a pull request

**Comment by nijel** [comment]
Thanks!
