### ISSUE TITLE
Error at /accounts/register/ - [Errno 111] 

### ISSUE THREAD

**Issue by lcpriest** [nijel/weblate-docker#5]
Looks to be the same as https://github.com/nijel/weblate/issues/628.

```
weblate_1  | error: [Errno 111] Connection refused
weblate_1  | ERROR:django.request:Internal Server Error: /accounts/register/
weblate_1  | Traceback (most recent call last):
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
weblate_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/weblate/accounts/views.py", line 422, in register
weblate_1  |     return complete(request, 'email')
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
weblate_1  |     response = view_func(request, *args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
weblate_1  |     return view_func(*args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 51, in wrapper
weblate_1  |     return func(request, backend, *args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/apps/django_app/views.py", line 28, in complete
weblate_1  |     redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/actions.py", line 43, in do_complete
weblate_1  |     user = backend.complete(user=user, *args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/backends/base.py", line 41, in complete
weblate_1  |     return self.auth_complete(*args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/backends/legacy.py", line 25, in auth_complete
weblate_1  |     return self.strategy.authenticate(*args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/strategies/django_strategy.py", line 96, in authenticate
weblate_1  |     return authenticate(*args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
weblate_1  |     user = backend.authenticate(**credentials)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/backends/base.py", line 82, in authenticate
weblate_1  |     return self.pipeline(pipeline, *args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/backends/base.py", line 85, in pipeline
weblate_1  |     out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/backends/base.py", line 112, in run_pipeline
weblate_1  |     result = func(*args, **out) or {}
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/pipeline/partial.py", line 15, in wrapper
weblate_1  |     *args, **kwargs) or {}
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/pipeline/mail.py", line 19, in mail_validation
weblate_1  |     backend.strategy.send_email_validation(backend, details['email'])
weblate_1  |   File "/app/local/lib/python2.7/site-packages/social/strategies/base.py", line 127, in send_email_validation
weblate_1  |     send_email(self, backend, code)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/weblate/accounts/pipeline.py", line 114, in send_validation
weblate_1  |     'url': url
weblate_1  |   File "/app/local/lib/python2.7/site-packages/weblate/accounts/models.py", line 359, in send_notification_email
weblate_1  |     send_mails([email])
weblate_1  |   File "/app/local/lib/python2.7/site-packages/weblate/accounts/models.py", line 54, in send_mails
weblate_1  |     connection.send_messages(mails)
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
weblate_1  |     new_conn_created = self.open()
weblate_1  |   File "/app/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 58, in open
weblate_1  |     self.connection = connection_class(self.host, self.port, **connection_params)
weblate_1  |   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
weblate_1  |     (code, msg) = self.connect(host, port)
weblate_1  |   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
weblate_1  |     self.sock = self._get_socket(host, port, self.timeout)
weblate_1  |   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
weblate_1  |     return socket.create_connection((host, port), timeout)
weblate_1  |   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
weblate_1  |     raise err
```

**Comment by nijel** [comment]
Ah, the SMTP server is not configured...

**Comment by funilrys** [comment]
Just a clarification, I solve it with install and configuration of `postfix` :)

**Comment by nijel** [comment]
You can also set [WEBLATE_EMAIL_HOST](https://docs.weblate.org/en/latest/admin/deployments.html#envvar-WEBLATE_EMAIL_HOST) to use external SMTP server.

**Comment by funilrys** [comment]
Does it work with installation from source @nijel ?

**Comment by nijel** [comment]
Yes, it's just called differently, see https://docs.weblate.org/en/latest/admin/install.html#outgoing-mail

**Comment by funilrys** [comment]
Already tested @nijel and didn't work with gmail ...

**Comment by nijel** [comment]
You probably need to disable captcha prior using this, see http://stackoverflow.com/a/34110999/225718
